server:
  port: 8089
  servlet:
    context-path: /
  # 支持流式输出的配置
  undertow:
    io-threads: 16
    worker-threads: 256
  # 或者如果使用Tomcat
  tomcat:
    connection-timeout: 20000
    keep-alive-timeout: 15000

spring:
  datasource:
    url: jdbc:mysql://160.202.227.209:3306/pddweb?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: admin
    password: 20031216Yxz
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    # 支持异步请求
    async:
      request-timeout: 300000  # 5分钟超时
  # 支持流式输出
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # HTTP编码配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pdd.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

